TITLE Mod file for component: Component(id=can type=ionChannelHH)

COMMENT

    This NEURON file has been generated by org.neuroml.export (see https://github.com/NeuroML/org.neuroml.export)
         org.neuroml.export  v1.11.0
         org.neuroml.model   v1.11.0
         jLEMS               v0.12.0

ENDCOMMENT

NEURON {
    SUFFIX can_nml
    USEION ca READ cai, cao WRITE ica VALENCE 2 ? Assuming valence = 2 (Ca ion); TODO check this!!
    
    RANGE gion
    RANGE i__can : a copy of the variable for current which makes it easier to access from outside the mod file
    RANGE gmax                              : Will be changed when ion channel mechanism placed on cell!
    
    RANGE cai
    RANGE cao
    RANGE conductance                       : parameter
    RANGE g                                 : exposure
    RANGE fopen                             : exposure
    RANGE ConductanceScalingCaDependent_CONC_SCALE: parameter
    RANGE ConductanceScalingCaDependent_ki  : parameter
    RANGE ConductanceScalingCaDependent_factor: exposure
    RANGE m_instances                       : parameter
    RANGE m_alpha                           : exposure
    RANGE m_beta                            : exposure
    RANGE m_tau                             : exposure
    RANGE m_inf                             : exposure
    RANGE m_rateScale                       : exposure
    RANGE m_fcond                           : exposure
    RANGE m_forwardRate_rate                : parameter
    RANGE m_forwardRate_midpoint            : parameter
    RANGE m_forwardRate_scale               : parameter
    RANGE m_forwardRate_r                   : exposure
    RANGE m_reverseRate_rate                : parameter
    RANGE m_reverseRate_midpoint            : parameter
    RANGE m_reverseRate_scale               : parameter
    RANGE m_reverseRate_r                   : exposure
    RANGE m_timeCourse_TIME_SCALE           : parameter
    RANGE m_timeCourse_VOLT_SCALE           : parameter
    RANGE m_timeCourse_mmin                 : parameter
    RANGE m_timeCourse_a0m                  : parameter
    RANGE m_timeCourse_zetam                : parameter
    RANGE m_timeCourse_gmm                  : parameter
    RANGE m_timeCourse_vhalfm               : parameter
    RANGE m_timeCourse_t                    : exposure
    RANGE m_q10Settings_q10Factor           : parameter
    RANGE m_q10Settings_experimentalTemp    : parameter
    RANGE m_q10Settings_TENDEGREES          : parameter
    RANGE m_q10Settings_q10                 : exposure
    RANGE h_instances                       : parameter
    RANGE h_alpha                           : exposure
    RANGE h_beta                            : exposure
    RANGE h_tau                             : exposure
    RANGE h_inf                             : exposure
    RANGE h_rateScale                       : exposure
    RANGE h_fcond                           : exposure
    RANGE h_forwardRate_rate                : parameter
    RANGE h_forwardRate_midpoint            : parameter
    RANGE h_forwardRate_scale               : parameter
    RANGE h_forwardRate_r                   : exposure
    RANGE h_reverseRate_rate                : parameter
    RANGE h_reverseRate_midpoint            : parameter
    RANGE h_reverseRate_scale               : parameter
    RANGE h_reverseRate_r                   : exposure
    RANGE h_timeCourse_TIME_SCALE           : parameter
    RANGE h_timeCourse_t                    : exposure
    RANGE h_q10Settings_q10Factor           : parameter
    RANGE h_q10Settings_experimentalTemp    : parameter
    RANGE h_q10Settings_TENDEGREES          : parameter
    RANGE h_q10Settings_q10                 : exposure
    RANGE ConductanceScalingCaDependent_ca_conc: derived variable
    RANGE m_forwardRate_x                   : derived variable
    RANGE m_timeCourse_V                    : derived variable
    RANGE m_tauUnscaled                     : derived variable
    RANGE h_tauUnscaled                     : derived variable
    RANGE conductanceScale                  : derived variable
    RANGE fopen0                            : derived variable
    
}

UNITS {
    
    (nA) = (nanoamp)
    (uA) = (microamp)
    (mA) = (milliamp)
    (A) = (amp)
    (mV) = (millivolt)
    (mS) = (millisiemens)
    (uS) = (microsiemens)
    (nF) = (nanofarad)
    (molar) = (1/liter)
    (kHz) = (kilohertz)
    (mM) = (millimolar)
    (um) = (micrometer)
    (umol) = (micromole)
    (pC) = (picocoulomb)
    (S) = (siemens)
    : bypass nrn default faraday const
    FARADAY = 96485.3 (coulomb)
    R = (k-mole) (joule/degC)
    
}

PARAMETER {
    
    gmax = 0  (S/cm2)                       : Will be changed when ion channel mechanism placed on cell!
    
    ki=.001 (mM)
    
    conductance = 1.0E-5 (uS)              : was: 1.0E-11 (conductance)
    ConductanceScalingCaDependent_CONC_SCALE = 1 (mM): was: 1.0 (concentration)
    ConductanceScalingCaDependent_ki = 0.001 : was: 0.001 (none)
    m_instances = 2                        : was: 2.0 (none)
    m_forwardRate_rate = 1.9670001 (kHz)   : was: 1967.0 (per_time)
    m_forwardRate_midpoint = 19.88 (mV)    : was: 0.01988 (voltage)
    m_forwardRate_scale = 10 (mV)          : was: 0.01 (voltage)
    m_reverseRate_rate = 0.046000004 (kHz) : was: 46.0 (per_time)
    m_reverseRate_midpoint = 0 (mV)        : was: 0.0 (voltage)
    m_reverseRate_scale = -20.73 (mV)      : was: -0.020730000000000002 (voltage)
    m_timeCourse_TIME_SCALE = 1 (ms)       : was: 0.001 (time)
    m_timeCourse_VOLT_SCALE = 1 (mV)       : was: 0.001 (voltage)
    m_timeCourse_mmin = 0.2 (ms)           : was: 2.0E-4 (time)
    m_timeCourse_a0m = 0.03                : was: 0.03 (none)
    m_timeCourse_zetam = 2                 : was: 2.0 (none)
    m_timeCourse_gmm = 0.1                 : was: 0.1 (none)
    m_timeCourse_vhalfm = -14              : was: -14.0 (none)
    m_q10Settings_q10Factor = 5            : was: 5.0 (none)
    m_q10Settings_experimentalTemp = 298.15 (K): was: 298.15 (temperature)
    m_q10Settings_TENDEGREES = 10 (K)      : was: 10.0 (temperature)
    h_instances = 1                        : was: 1.0 (none)
    h_forwardRate_rate = 1.6000001E-4 (kHz): was: 0.16 (per_time)
    h_forwardRate_midpoint = 0 (mV)        : was: 0.0 (voltage)
    h_forwardRate_scale = -48.4 (mV)       : was: -0.0484 (voltage)
    h_reverseRate_rate = 1 (kHz)           : was: 1000.0 (per_time)
    h_reverseRate_midpoint = 39 (mV)       : was: 0.039 (voltage)
    h_reverseRate_scale = 10 (mV)          : was: 0.01 (voltage)
    h_timeCourse_TIME_SCALE = 1 (ms)       : was: 0.001 (time)
    h_q10Settings_q10Factor = 1            : was: 5.0 (none)
    h_q10Settings_experimentalTemp = 298.15 (K): was: 298.15 (temperature)
    h_q10Settings_TENDEGREES = 10 (K)      : was: 10.0 (temperature)
}

ASSIGNED {
    
    gion   (S/cm2)                          : Transient conductance density of the channel? Standard Assigned variables with ionChannel
    v (mV)
    celsius (degC)
    temperature (K)
    eca (mV)
    ica (mA/cm2)
    i__can (mA/cm2)
    
    cai (mM)
    
    cao (mM)
    
    ConductanceScalingCaDependent_ca_conc   : derived variable
    ConductanceScalingCaDependent_factor    : derived variable
    m_forwardRate_x                         : derived variable
    
    m_forwardRate_r (kHz)                   : conditional derived var...
    m_reverseRate_r (kHz)                   : derived variable
    m_timeCourse_V                          : derived variable
    
    m_timeCourse_t (ms)                     : conditional derived var...
    m_q10Settings_q10                       : derived variable
    m_rateScale                             : derived variable
    m_alpha (kHz)                           : derived variable
    m_beta (kHz)                            : derived variable
    m_fcond                                 : derived variable
    m_inf                                   : derived variable
    m_tauUnscaled (ms)                      : derived variable
    m_tau (ms)                              : derived variable
    h_forwardRate_r (kHz)                   : derived variable
    h_reverseRate_r (kHz)                   : derived variable
    h_timeCourse_t (ms)                     : derived variable
    h_q10Settings_q10                       : derived variable
    h_rateScale                             : derived variable
    h_alpha (kHz)                           : derived variable
    h_beta (kHz)                            : derived variable
    h_fcond                                 : derived variable
    h_inf                                   : derived variable
    h_tauUnscaled (ms)                      : derived variable
    h_tau (ms)                              : derived variable
    conductanceScale                        : derived variable
    fopen0                                  : derived variable
    fopen                                   : derived variable
    g (uS)                                  : derived variable
    rate_m_q (/ms)
    rate_h_q (/ms)
    
}

STATE {
    m_q  : dimension: none
    h_q  : dimension: none
    
}

INITIAL {
    temperature = celsius + 273.15
    
    rates()
    rates() ? To ensure correct initialisation.
    
    m_q = m_inf
    
    h_q = h_inf
    
}

BREAKPOINT {
    
    SOLVE states METHOD cnexp
    m_fcond = m_q ^ m_instances
    h_fcond = h_q ^ h_instances
    
    ? DerivedVariable is based on path: conductanceScaling[*]/factor, on: Component(id=can type=ionChannelHH), from conductanceScaling; Component(id=null type=can_scale)
    ? multiply applied to all instances of factor in: <conductanceScaling> ([Component(id=null type=can_scale)]))
    conductanceScale = ConductanceScalingCaDependent_factor ? path based, prefix = 
    
    ? DerivedVariable is based on path: gates[*]/fcond, on: Component(id=can type=ionChannelHH), from gates; Component(id=m type=gateHHratesTau)
    ? multiply applied to all instances of fcond in: <gates> ([Component(id=m type=gateHHratesTau), Component(id=h type=gateHHratesTau)]))
    fopen0 = m_fcond * h_fcond ? path based, prefix = 
    
    fopen = conductanceScale  *  fopen0 ? evaluable
    g = conductance  *  fopen ? evaluable
    gion = gmax * fopen
    
    ica = gion * ghk2(v, cai, cao)
    i__can =  -1 * ica : set this variable to the current also - note -1 as channel current convention for LEMS used!
    
}

DERIVATIVE states {
    rates()
    m_q' = ( m_inf  -  m_q ) /  m_tau 
    h_q' = ( h_inf  -  h_q ) /  h_tau 
    
}

PROCEDURE rates() {
    LOCAL caConc
    
    caConc = cai
    
    ConductanceScalingCaDependent_ca_conc = caConc /  ConductanceScalingCaDependent_CONC_SCALE ? evaluable
    ConductanceScalingCaDependent_factor = ConductanceScalingCaDependent_ki  / ( ConductanceScalingCaDependent_ki  +  ConductanceScalingCaDependent_ca_conc ) ? evaluable
    m_forwardRate_x = (v -  m_forwardRate_midpoint ) /  m_forwardRate_scale ? evaluable
    if (m_forwardRate_x  != 0)  { 
        m_forwardRate_r = m_forwardRate_rate  *  m_forwardRate_x  / (1 - exp(0 -  m_forwardRate_x )) ? evaluable cdv
    } else if (m_forwardRate_x  == 0)  { 
        m_forwardRate_r = m_forwardRate_rate ? evaluable cdv
    }
    
    m_reverseRate_r = m_reverseRate_rate  * exp((v -  m_reverseRate_midpoint )/ m_reverseRate_scale ) ? evaluable
    m_timeCourse_V = v /  m_timeCourse_VOLT_SCALE ? evaluable
    if (exp(0.0378 *  m_timeCourse_zetam  *  m_timeCourse_gmm  * ( m_timeCourse_V  -  m_timeCourse_vhalfm )) / ( m_timeCourse_a0m  * (1 + exp(0.0378 *  m_timeCourse_zetam  * ( m_timeCourse_V  -  m_timeCourse_vhalfm )))) *  m_timeCourse_TIME_SCALE  <  m_timeCourse_mmin)  { 
        m_timeCourse_t = m_timeCourse_mmin ? evaluable cdv
    } else  { 
        m_timeCourse_t = exp(0.0378 *  m_timeCourse_zetam  *  m_timeCourse_gmm  * ( m_timeCourse_V  -  m_timeCourse_vhalfm )) / ( m_timeCourse_a0m  * (1 + exp(0.0378 *  m_timeCourse_zetam  * ( m_timeCourse_V  -  m_timeCourse_vhalfm )))) *  m_timeCourse_TIME_SCALE ? evaluable cdv
    }
    
    m_q10Settings_q10 = m_q10Settings_q10Factor ^((temperature -  m_q10Settings_experimentalTemp )/ m_q10Settings_TENDEGREES ) ? evaluable
    ? DerivedVariable is based on path: q10Settings[*]/q10, on: Component(id=m type=gateHHratesTau), from q10Settings; Component(id=null type=q10ExpTemp)
    ? multiply applied to all instances of q10 in: <q10Settings> ([Component(id=null type=q10ExpTemp)]))
    m_rateScale = m_q10Settings_q10 ? path based, prefix = m_
    
    ? DerivedVariable is based on path: forwardRate/r, on: Component(id=m type=gateHHratesTau), from forwardRate; Component(id=null type=HHExpLinearRate)
    m_alpha = m_forwardRate_r ? path based, prefix = m_
    
    ? DerivedVariable is based on path: reverseRate/r, on: Component(id=m type=gateHHratesTau), from reverseRate; Component(id=null type=HHExpRate)
    m_beta = m_reverseRate_r ? path based, prefix = m_
    
    m_fcond = m_q ^ m_instances ? evaluable
    m_inf = m_alpha /( m_alpha + m_beta ) ? evaluable
    ? DerivedVariable is based on path: timeCourse/t, on: Component(id=m type=gateHHratesTau), from timeCourse; Component(id=null type=can_m_tau)
    m_tauUnscaled = m_timeCourse_t ? path based, prefix = m_
    
    m_tau = m_tauUnscaled  /  m_rateScale ? evaluable
    h_forwardRate_r = h_forwardRate_rate  * exp((v -  h_forwardRate_midpoint )/ h_forwardRate_scale ) ? evaluable
    h_reverseRate_r = h_reverseRate_rate  / (1 + exp(0 - (v -  h_reverseRate_midpoint )/ h_reverseRate_scale )) ? evaluable
    h_timeCourse_t = 80 *  h_timeCourse_TIME_SCALE ? evaluable
    h_q10Settings_q10 = h_q10Settings_q10Factor ^((temperature -  h_q10Settings_experimentalTemp )/ h_q10Settings_TENDEGREES ) ? evaluable
    ? DerivedVariable is based on path: q10Settings[*]/q10, on: Component(id=h type=gateHHratesTau), from q10Settings; Component(id=null type=q10ExpTemp)
    ? multiply applied to all instances of q10 in: <q10Settings> ([Component(id=null type=q10ExpTemp)]))
    h_rateScale = h_q10Settings_q10 ? path based, prefix = h_
    
    ? DerivedVariable is based on path: forwardRate/r, on: Component(id=h type=gateHHratesTau), from forwardRate; Component(id=null type=HHExpRate)
    h_alpha = h_forwardRate_r ? path based, prefix = h_
    
    ? DerivedVariable is based on path: reverseRate/r, on: Component(id=h type=gateHHratesTau), from reverseRate; Component(id=null type=HHSigmoidRate)
    h_beta = h_reverseRate_r ? path based, prefix = h_
    
    h_fcond = h_q ^ h_instances ? evaluable
    h_inf = h_alpha /( h_alpha + h_beta ) ? evaluable
    ? DerivedVariable is based on path: timeCourse/t, on: Component(id=h type=gateHHratesTau), from timeCourse; Component(id=null type=can_h_tau)
    h_tauUnscaled = h_timeCourse_t ? path based, prefix = h_
    
    h_tau = h_tauUnscaled  /  h_rateScale ? evaluable
    
     
    
     
    rate_m_q = ( m_inf  -  m_q ) /  m_tau ? Note units of all quantities used here need to be consistent!
    
     
    
     
    
     
    
     
    
     
    rate_h_q = ( h_inf  -  h_q ) /  h_tau ? Note units of all quantities used here need to be consistent!
    
     
    
     
    
     
    
     
    
     
    
}


FUNCTION ghk2(v(mV), ci(mM), co(mM)) (mV) {
        LOCAL nu,f

        f = KTF(celsius)/2
        nu = v/f
        ghk2=-f*(1. - (ci/co)*exp(nu))*efun(nu)
}

FUNCTION KTF(celsius (DegC)) (mV) {
        KTF = ((25./293.15)*(celsius + 273.15))
}

FUNCTION efun(z) {
	if (fabs(z) < 1e-4) {
		efun = 1 - z/2
	}else{
		efun = z/(exp(z) - 1)
	}
}
