TITLE Mod file for component: Component(id=kBK type=ionChannelHH)

COMMENT

    This NEURON file has been generated by org.neuroml.export (see https://github.com/NeuroML/org.neuroml.export)
         org.neuroml.export  v1.11.0
         org.neuroml.model   v1.11.0
         jLEMS               v0.12.0

ENDCOMMENT

NEURON {
	SUFFIX kBK_nml
    USEION ca READ cai,cao VALENCE 2
    USEION k WRITE ik VALENCE 1 ? Assuming valence = 1; TODO check this!!
    
    RANGE gion
    RANGE i__kBK : a copy of the variable for current which makes it easier to access from outside the mod file
    RANGE gmax                              : Will be changed when ion channel mechanism placed on cell!
    RANGE conductance                       : parameter
    RANGE g                                 : exposure
    RANGE fopen                             : exposure
    RANGE p_instances                       : parameter
    RANGE p_tau                             : exposure
    RANGE p_inf                             : exposure
    RANGE p_rateScale                       : exposure
    RANGE p_fcond                           : exposure
    RANGE p_steadyState_TIME_SCALE          : parameter
    RANGE p_steadyState_VOLT_SCALE          : parameter
    RANGE p_steadyState_CONC_SCALE          : parameter
    RANGE p_steadyState_caPh                : parameter
    RANGE p_steadyState_caVhmin             : parameter
    RANGE p_steadyState_caVhmax             : parameter
    RANGE p_steadyState_caVhh               : parameter
    RANGE p_steadyState_caVhk               : parameter
    RANGE p_steadyState_x                   : exposure
    RANGE p_timeCourse_tau                  : parameter
    RANGE p_timeCourse_t                    : exposure
    RANGE p_steadyState_V                   : derived variable
    RANGE p_steadyState_ca_conc             : derived variable
    RANGE p_tauUnscaled                     : derived variable
    RANGE conductanceScale                  : derived variable
    RANGE fopen0                            : derived variable
    
}

UNITS {
    
    (nA) = (nanoamp)
    (uA) = (microamp)
    (mA) = (milliamp)
    (A) = (amp)
    (mV) = (millivolt)
    (mS) = (millisiemens)
    (uS) = (microsiemens)
    (nF) = (nanofarad)
    (molar) = (1/liter)
    (kHz) = (kilohertz)
    (mM) = (millimolar)
    (um) = (micrometer)
    (umol) = (micromole)
    (pC) = (picocoulomb)
    (S) = (siemens)
    
}

PARAMETER {
    
    gmax = 0  (S/cm2)                       : Will be changed when ion channel mechanism placed on cell!
    
    conductance = 1.0E-5 (uS)              : was: 1.0E-11 (conductance)
    p_instances = 1                        : was: 1.0 (none)
    p_steadyState_TIME_SCALE = 1 (ms)      : was: 0.001 (time)
    p_steadyState_VOLT_SCALE = 1 (mV)      : was: 0.001 (voltage)
    p_steadyState_CONC_SCALE = 1 (mM)      : was: 1.0 (concentration)
    p_steadyState_caPh = 0.002             : was: 0.002 (none)
    p_steadyState_caVhmin = 43.919144      : was: 43.919142291200004 (none)
    p_steadyState_caVhmax = 155.67         : was: 155.67 (none)
    p_steadyState_caVhh = 0.002            : was: 0.002 (none)
    p_steadyState_caVhk = -0.94208         : was: -0.94208 (none)
    p_timeCourse_tau = 1 (ms)              : was: 0.001 (time)
}

ASSIGNED {
    
    gion   (S/cm2)                          : Transient conductance density of the channel? Standard Assigned variables with ionChannel
    v (mV)
    celsius (degC)
    temperature (K)
    ek (mV)
    ik (mA/cm2)
    i__kBK (mA/cm2)
    
    cai (mM)
    
    cao (mM)
    
    p_steadyState_V                         : derived variable
    p_steadyState_ca_conc                   : derived variable
    
    p_steadyState_x                         : conditional derived var...
    p_timeCourse_t (ms)                     : derived variable
    p_rateScale                             : derived variable
    p_fcond                                 : derived variable
    p_inf                                   : derived variable
    p_tauUnscaled (ms)                      : derived variable
    p_tau (ms)                              : derived variable
    conductanceScale                        : derived variable
    fopen0                                  : derived variable
    fopen                                   : derived variable
    g (uS)                                  : derived variable
    rate_p_q (/ms)
    
}

STATE {
    p_q  : dimension: none
    
}

INITIAL {
    ek = -104.0
    
    temperature = celsius + 273.15
    
    rates()
    rates() ? To ensure correct initialisation.
    
    p_q = p_inf
    
}

BREAKPOINT {
    
    SOLVE states METHOD cnexp
    p_fcond = p_q ^ p_instances
    
    ? DerivedVariable is based on path: conductanceScaling[*]/factor, on: Component(id=kBK type=ionChannelHH), from conductanceScaling; null
    ? Path not present in component, using factor: 1
    
    conductanceScale = 1 
    
    ? DerivedVariable is based on path: gates[*]/fcond, on: Component(id=kBK type=ionChannelHH), from gates; Component(id=p type=gateHHtauInf)
    ? multiply applied to all instances of fcond in: <gates> ([Component(id=p type=gateHHtauInf)]))
    fopen0 = p_fcond ? path based, prefix = 
    
    fopen = conductanceScale  *  fopen0 ? evaluable
    g = conductance  *  fopen ? evaluable
    gion = gmax * fopen 
    
    ik = gion * (v - ek)
    i__kBK =  -1 * ik : set this variable to the current also - note -1 as channel current convention for LEMS used!
    
}

DERIVATIVE states {
    rates()
    p_q' = ( p_inf  -  p_q ) /  p_tau 
    
}

PROCEDURE rates() {
    LOCAL caConc
    
    caConc = cai
    
    p_steadyState_V = v /  p_steadyState_VOLT_SCALE ? evaluable
    p_steadyState_ca_conc = caConc /  p_steadyState_CONC_SCALE ? evaluable
    if (p_steadyState_ca_conc  < 1e-18)  { 
        p_steadyState_x = 0 ? evaluable cdv
    } else  { 
        p_steadyState_x = (1 / ( 1 +  p_steadyState_caPh  / (100 *  p_steadyState_ca_conc ))) / (1 + exp((( p_steadyState_caVhmin  + ( ( p_steadyState_caVhmax  -  p_steadyState_caVhmin  ) / ( 1 + (( p_steadyState_caVhh /(100 *  p_steadyState_ca_conc ))^ p_steadyState_caVhk )) )) -  p_steadyState_V )/17)) ? evaluable cdv
    }
    
    p_timeCourse_t = p_timeCourse_tau ? evaluable
    ? DerivedVariable is based on path: q10Settings[*]/q10, on: Component(id=p type=gateHHtauInf), from q10Settings; null
    ? Path not present in component, using factor: 1
    
    p_rateScale = 1 
    
    p_fcond = p_q ^ p_instances ? evaluable
    ? DerivedVariable is based on path: steadyState/x, on: Component(id=p type=gateHHtauInf), from steadyState; Component(id=null type=kBK_p_inf)
    p_inf = p_steadyState_x ? path based, prefix = p_
    
    ? DerivedVariable is based on path: timeCourse/t, on: Component(id=p type=gateHHtauInf), from timeCourse; Component(id=null type=fixedTimeCourse)
    p_tauUnscaled = p_timeCourse_t ? path based, prefix = p_
    
    p_tau = p_tauUnscaled  /  p_rateScale ? evaluable
    
     
    rate_p_q = ( p_inf  -  p_q ) /  p_tau ? Note units of all quantities used here need to be consistent!
    
     
    
     
    
     
    
}
