TITLE Mod file for component: Component(id=nax type=ionChannelHH)

COMMENT

    This NEURON file has been generated by org.neuroml.export (see https://github.com/NeuroML/org.neuroml.export)
         org.neuroml.export  v1.11.0
         org.neuroml.model   v1.11.0
         jLEMS               v0.12.0

ENDCOMMENT

NEURON {
	SUFFIX nax_nml
    USEION na WRITE ina VALENCE 1 ? Assuming valence = 1; TODO check this!!
    
    RANGE gion
    RANGE i__nax : a copy of the variable for current which makes it easier to access from outside the mod file
    RANGE gmax                              : Will be changed when ion channel mechanism placed on cell!
    RANGE conductance                       : parameter
    RANGE g                                 : exposure
    RANGE fopen                             : exposure
    RANGE m_instances                       : parameter
    RANGE m_alpha                           : exposure
    RANGE m_beta                            : exposure
    RANGE m_tau                             : exposure
    RANGE m_inf                             : exposure
    RANGE m_rateScale                       : exposure
    RANGE m_fcond                           : exposure
    RANGE m_forwardRate_TIME_SCALE          : parameter
    RANGE m_forwardRate_VOLT_SCALE          : parameter
    RANGE m_forwardRate_Ra                  : parameter
    RANGE m_forwardRate_qa                  : parameter
    RANGE m_forwardRate_tha                 : parameter
    RANGE m_forwardRate_sh                  : parameter
    RANGE m_forwardRate_r                   : exposure
    RANGE m_reverseRate_TIME_SCALE          : parameter
    RANGE m_reverseRate_VOLT_SCALE          : parameter
    RANGE m_reverseRate_Rb                  : parameter
    RANGE m_reverseRate_qa                  : parameter
    RANGE m_reverseRate_tha                 : parameter
    RANGE m_reverseRate_sh                  : parameter
    RANGE m_reverseRate_r                   : exposure
    RANGE m_timeCourse_TIME_SCALE           : parameter
    RANGE m_timeCourse_VOLT_SCALE           : parameter
    RANGE m_timeCourse_mmin                 : parameter
    RANGE m_timeCourse_t                    : exposure
    RANGE m_q10Settings_q10Factor           : parameter
    RANGE m_q10Settings_experimentalTemp    : parameter
    RANGE m_q10Settings_TENDEGREES          : parameter
    RANGE m_q10Settings_q10                 : exposure
    RANGE h_instances                       : parameter
    RANGE h_alpha                           : exposure
    RANGE h_beta                            : exposure
    RANGE h_tau                             : exposure
    RANGE h_inf                             : exposure
    RANGE h_rateScale                       : exposure
    RANGE h_fcond                           : exposure
    RANGE h_forwardRate_TIME_SCALE          : parameter
    RANGE h_forwardRate_VOLT_SCALE          : parameter
    RANGE h_forwardRate_Rd                  : parameter
    RANGE h_forwardRate_qd                  : parameter
    RANGE h_forwardRate_thi1                : parameter
    RANGE h_forwardRate_sh                  : parameter
    RANGE h_forwardRate_r                   : exposure
    RANGE h_reverseRate_TIME_SCALE          : parameter
    RANGE h_reverseRate_VOLT_SCALE          : parameter
    RANGE h_reverseRate_Rg                  : parameter
    RANGE h_reverseRate_qg                  : parameter
    RANGE h_reverseRate_thi2                : parameter
    RANGE h_reverseRate_sh                  : parameter
    RANGE h_reverseRate_r                   : exposure
    RANGE h_steadyState_rate                : parameter
    RANGE h_steadyState_midpoint            : parameter
    RANGE h_steadyState_scale               : parameter
    RANGE h_steadyState_x                   : exposure
    RANGE h_timeCourse_TIME_SCALE           : parameter
    RANGE h_timeCourse_VOLT_SCALE           : parameter
    RANGE h_timeCourse_hmin                 : parameter
    RANGE h_timeCourse_t                    : exposure
    RANGE h_q10Settings_q10Factor           : parameter
    RANGE h_q10Settings_experimentalTemp    : parameter
    RANGE h_q10Settings_TENDEGREES          : parameter
    RANGE h_q10Settings_q10                 : exposure
    RANGE m_forwardRate_V                   : derived variable
    RANGE m_reverseRate_V                   : derived variable
    RANGE m_timeCourse_V                    : derived variable
    RANGE m_timeCourse_ALPHA                : derived variable
    RANGE m_timeCourse_BETA                 : derived variable
    RANGE m_tauUnscaled                     : derived variable
    RANGE h_forwardRate_V                   : derived variable
    RANGE h_reverseRate_V                   : derived variable
    RANGE h_timeCourse_V                    : derived variable
    RANGE h_timeCourse_ALPHA                : derived variable
    RANGE h_timeCourse_BETA                 : derived variable
    RANGE h_tauUnscaled                     : derived variable
    RANGE conductanceScale                  : derived variable
    RANGE fopen0                            : derived variable
    
}

UNITS {
    
    (nA) = (nanoamp)
    (uA) = (microamp)
    (mA) = (milliamp)
    (A) = (amp)
    (mV) = (millivolt)
    (mS) = (millisiemens)
    (uS) = (microsiemens)
    (nF) = (nanofarad)
    (molar) = (1/liter)
    (kHz) = (kilohertz)
    (mM) = (millimolar)
    (um) = (micrometer)
    (umol) = (micromole)
    (pC) = (picocoulomb)
    (S) = (siemens)
    
}

PARAMETER {
    
    gmax = 0  (S/cm2)                       : Will be changed when ion channel mechanism placed on cell!
    
    conductance = 1.0E-5 (uS)              : was: 1.0E-11 (conductance)
    m_instances = 3                        : was: 3.0 (none)
    m_forwardRate_TIME_SCALE = 1 (ms)      : was: 0.001 (time)
    m_forwardRate_VOLT_SCALE = 1 (mV)      : was: 0.001 (voltage)
    m_forwardRate_Ra = 0.4                 : was: 0.4 (none)
    m_forwardRate_qa = 7.2                 : was: 7.2 (none)
    m_forwardRate_tha = -30                : was: -30.0 (none)
    m_forwardRate_sh = 0                   : was: 0.0 (none)
    m_reverseRate_TIME_SCALE = 1 (ms)      : was: 0.001 (time)
    m_reverseRate_VOLT_SCALE = 1 (mV)      : was: 0.001 (voltage)
    m_reverseRate_Rb = 0.124               : was: 0.124 (none)
    m_reverseRate_qa = 7.2                 : was: 7.2 (none)
    m_reverseRate_tha = -30                : was: -30.0 (none)
    m_reverseRate_sh = 0                   : was: 0.0 (none)
    m_timeCourse_TIME_SCALE = 1 (ms)       : was: 0.001 (time)
    m_timeCourse_VOLT_SCALE = 1 (mV)       : was: 0.001 (voltage)
    m_timeCourse_mmin = 0.02               : was: 0.02 (none)
    m_q10Settings_q10Factor = 2            : was: 2.0 (none)
    m_q10Settings_experimentalTemp = 297.15 (K): was: 297.15 (temperature)
    m_q10Settings_TENDEGREES = 10 (K)      : was: 10.0 (temperature)
    h_instances = 1                        : was: 1.0 (none)
    h_forwardRate_TIME_SCALE = 1 (ms)      : was: 0.001 (time)
    h_forwardRate_VOLT_SCALE = 1 (mV)      : was: 0.001 (voltage)
    h_forwardRate_Rd = 0.03                : was: 0.03 (none)
    h_forwardRate_qd = 1.5                 : was: 1.5 (none)
    h_forwardRate_thi1 = -45               : was: -45.0 (none)
    h_forwardRate_sh = 0                   : was: 0.0 (none)
    h_reverseRate_TIME_SCALE = 1 (ms)      : was: 0.001 (time)
    h_reverseRate_VOLT_SCALE = 1 (mV)      : was: 0.001 (voltage)
    h_reverseRate_Rg = 0.01                : was: 0.01 (none)
    h_reverseRate_qg = 1.5                 : was: 1.5 (none)
    h_reverseRate_thi2 = -45               : was: -45.0 (none)
    h_reverseRate_sh = 0                   : was: 0.0 (none)
    h_steadyState_rate = 1                 : was: 1.0 (none)
    h_steadyState_midpoint = -50 (mV)      : was: -0.05 (voltage)
    h_steadyState_scale = -4 (mV)          : was: -0.004 (voltage)
    h_timeCourse_TIME_SCALE = 1 (ms)       : was: 0.001 (time)
    h_timeCourse_VOLT_SCALE = 1 (mV)       : was: 0.001 (voltage)
    h_timeCourse_hmin = 0.5                : was: 0.5 (none)
    h_q10Settings_q10Factor = 2            : was: 2.0 (none)
    h_q10Settings_experimentalTemp = 297.15 (K): was: 297.15 (temperature)
    h_q10Settings_TENDEGREES = 10 (K)      : was: 10.0 (temperature)
}

ASSIGNED {
    
    gion   (S/cm2)                          : Transient conductance density of the channel? Standard Assigned variables with ionChannel
    v (mV)
    celsius (degC)
    temperature (K)
    ena (mV)
    ina (mA/cm2)
    i__nax (mA/cm2)
    
    m_forwardRate_V                         : derived variable
    
    m_forwardRate_r (kHz)                   : conditional derived var...
    m_reverseRate_V                         : derived variable
    
    m_reverseRate_r (kHz)                   : conditional derived var...
    m_timeCourse_V                          : derived variable
    m_timeCourse_ALPHA                      : derived variable
    m_timeCourse_BETA                       : derived variable
    
    m_timeCourse_t (ms)                     : conditional derived var...
    m_q10Settings_q10                       : derived variable
    m_rateScale                             : derived variable
    m_alpha (kHz)                           : derived variable
    m_beta (kHz)                            : derived variable
    m_fcond                                 : derived variable
    m_inf                                   : derived variable
    m_tauUnscaled (ms)                      : derived variable
    m_tau (ms)                              : derived variable
    h_forwardRate_V                         : derived variable
    
    h_forwardRate_r (kHz)                   : conditional derived var...
    h_reverseRate_V                         : derived variable
    
    h_reverseRate_r (kHz)                   : conditional derived var...
    h_steadyState_x                         : derived variable
    h_timeCourse_V                          : derived variable
    h_timeCourse_ALPHA                      : derived variable
    h_timeCourse_BETA                       : derived variable
    
    h_timeCourse_t (ms)                     : conditional derived var...
    h_q10Settings_q10                       : derived variable
    h_rateScale                             : derived variable
    h_alpha (kHz)                           : derived variable
    h_beta (kHz)                            : derived variable
    h_inf                                   : derived variable
    h_tauUnscaled (ms)                      : derived variable
    h_tau (ms)                              : derived variable
    h_fcond                                 : derived variable
    conductanceScale                        : derived variable
    fopen0                                  : derived variable
    fopen                                   : derived variable
    g (uS)                                  : derived variable
    rate_m_q (/ms)
    rate_h_q (/ms)
    
}

STATE {
    m_q  : dimension: none
    h_q  : dimension: none
    
}

INITIAL {
    ena = 42.0
    
    temperature = celsius + 273.15
    
    rates()
    rates() ? To ensure correct initialisation.
    
    m_q = m_inf
    
    h_q = h_inf
    
}

BREAKPOINT {
    
    SOLVE states METHOD cnexp
    m_fcond = m_q ^ m_instances
    h_fcond = h_q ^ h_instances
    
    ? DerivedVariable is based on path: conductanceScaling[*]/factor, on: Component(id=nax type=ionChannelHH), from conductanceScaling; null
    ? Path not present in component, using factor: 1
    
    conductanceScale = 1 
    
    ? DerivedVariable is based on path: gates[*]/fcond, on: Component(id=nax type=ionChannelHH), from gates; Component(id=m type=gateHHratesTau)
    ? multiply applied to all instances of fcond in: <gates> ([Component(id=m type=gateHHratesTau), Component(id=h type=gateHHratesTauInf)]))
    fopen0 = m_fcond * h_fcond ? path based, prefix = 
    
    fopen = conductanceScale  *  fopen0 ? evaluable
    g = conductance  *  fopen ? evaluable
    gion = gmax * fopen 
    
    ina = gion * (v - ena)
    i__nax =  -1 * ina : set this variable to the current also - note -1 as channel current convention for LEMS used!
    
}

DERIVATIVE states {
    rates()
    m_q' = ( m_inf  -  m_q ) /  m_tau 
    h_q' = ( h_inf  -  h_q ) /  h_tau 
    
}

PROCEDURE rates() {
    
    m_forwardRate_V = v /  m_forwardRate_VOLT_SCALE ? evaluable
    if (( m_forwardRate_V  - ( m_forwardRate_tha  +  m_forwardRate_sh )) < 1.e-06 && ( m_forwardRate_V  - ( m_forwardRate_tha  +  m_forwardRate_sh )) > -1.e-06)  { 
        m_forwardRate_r = m_forwardRate_Ra  *  m_forwardRate_qa   /  m_forwardRate_TIME_SCALE ? evaluable cdv
    } else  { 
        m_forwardRate_r = m_forwardRate_Ra  * ( m_forwardRate_V  - ( m_forwardRate_tha  +  m_forwardRate_sh )) / (1 - exp(-( m_forwardRate_V  - ( m_forwardRate_tha  +  m_forwardRate_sh ))/ m_forwardRate_qa ))  /  m_forwardRate_TIME_SCALE ? evaluable cdv
    }
    
    m_reverseRate_V = v /  m_reverseRate_VOLT_SCALE ? evaluable
    if ((- m_reverseRate_V  +  m_reverseRate_tha  +  m_reverseRate_sh ) < 1.e-06 && (- m_reverseRate_V  +  m_reverseRate_tha  +  m_reverseRate_sh ) > -1.e-06)  { 
        m_reverseRate_r = m_reverseRate_Rb  *  m_reverseRate_qa  /  m_reverseRate_TIME_SCALE ? evaluable cdv
    } else  { 
        m_reverseRate_r = m_reverseRate_Rb  * (- m_reverseRate_V  +  m_reverseRate_tha  +  m_reverseRate_sh ) / (1 - exp(-(- m_reverseRate_V  +  m_reverseRate_tha  +  m_reverseRate_sh )/ m_reverseRate_qa )) /  m_reverseRate_TIME_SCALE ? evaluable cdv
    }
    
    m_q10Settings_q10 = m_q10Settings_q10Factor ^((temperature -  m_q10Settings_experimentalTemp )/ m_q10Settings_TENDEGREES ) ? evaluable
    ? DerivedVariable is based on path: q10Settings[*]/q10, on: Component(id=m type=gateHHratesTau), from q10Settings; Component(id=null type=q10ExpTemp)
    ? multiply applied to all instances of q10 in: <q10Settings> ([Component(id=null type=q10ExpTemp)]))
    m_rateScale = m_q10Settings_q10 ? path based, prefix = m_
    
    ? DerivedVariable is based on path: forwardRate/r, on: Component(id=m type=gateHHratesTau), from forwardRate; Component(id=null type=nax_m_alpha_rate)
    m_alpha = m_forwardRate_r ? path based, prefix = m_
    
    ? DerivedVariable is based on path: reverseRate/r, on: Component(id=m type=gateHHratesTau), from reverseRate; Component(id=null type=nax_m_beta_rate)
    m_beta = m_reverseRate_r ? path based, prefix = m_
    
    m_timeCourse_V = v /  m_timeCourse_VOLT_SCALE
    m_timeCourse_ALPHA = m_alpha  *  m_timeCourse_TIME_SCALE
    m_timeCourse_BETA = m_beta  *  m_timeCourse_TIME_SCALE
    if (( m_timeCourse_ALPHA  +  m_timeCourse_BETA ) == 0)  { 
        m_timeCourse_t = m_timeCourse_mmin  *  m_timeCourse_TIME_SCALE
    } else  { 
        m_timeCourse_t = 1/( m_timeCourse_ALPHA + m_timeCourse_BETA ) *  m_timeCourse_TIME_SCALE
    }
    
    m_inf = m_alpha /( m_alpha + m_beta ) ? evaluable
    ? DerivedVariable is based on path: timeCourse/t, on: Component(id=m type=gateHHratesTau), from timeCourse; Component(id=null type=nax_m_tau)
    m_tauUnscaled = m_timeCourse_t / m_rateScale
    if (m_tauUnscaled < m_timeCourse_mmin) {
        m_tau = m_timeCourse_mmin
    } else {
        m_tau = m_tauUnscaled
    }
    h_forwardRate_V = v /  h_forwardRate_VOLT_SCALE ? evaluable
    if (( h_forwardRate_V  - ( h_forwardRate_thi1  +  h_forwardRate_sh )) < 1.e-06 && ( h_forwardRate_V  - ( h_forwardRate_thi1  +  h_forwardRate_sh )) > -1.e-06)  { 
        h_forwardRate_r = h_forwardRate_Rd  *  h_forwardRate_qd   /  h_forwardRate_TIME_SCALE ? evaluable cdv
    } else  { 
        h_forwardRate_r = h_forwardRate_Rd  * ( h_forwardRate_V  - ( h_forwardRate_thi1  +  h_forwardRate_sh )) / (1 - exp(-( h_forwardRate_V  - ( h_forwardRate_thi1  +  h_forwardRate_sh ))/ h_forwardRate_qd )) /  h_forwardRate_TIME_SCALE ? evaluable cdv
    }
    
    h_reverseRate_V = v /  h_reverseRate_VOLT_SCALE ? evaluable
    if ((- h_reverseRate_V  +  h_reverseRate_thi2  +  h_reverseRate_sh ) < 1.e-06 && (- h_reverseRate_V  +  h_reverseRate_thi2  +  h_reverseRate_sh ) > -1.e-06)  { 
        h_reverseRate_r = h_reverseRate_Rg  *  h_reverseRate_qg   /  h_reverseRate_TIME_SCALE ? evaluable cdv
    } else  { 
        h_reverseRate_r = h_reverseRate_Rg  * (- h_reverseRate_V  +  h_reverseRate_thi2  +  h_reverseRate_sh ) / (1 - exp(-(- h_reverseRate_V  +  h_reverseRate_thi2  +  h_reverseRate_sh )/ h_reverseRate_qg ))  / h_reverseRate_TIME_SCALE ? evaluable cdv
    }
    
    h_q10Settings_q10 = h_q10Settings_q10Factor ^((temperature -  h_q10Settings_experimentalTemp )/ h_q10Settings_TENDEGREES ) ? evaluable
    ? DerivedVariable is based on path: q10Settings[*]/q10, on: Component(id=h type=gateHHratesTauInf), from q10Settings; Component(id=null type=q10ExpTemp)
    ? multiply applied to all instances of q10 in: <q10Settings> ([Component(id=null type=q10ExpTemp)]))
    h_rateScale = h_q10Settings_q10 ? path based, prefix = h_
    
    ? DerivedVariable is based on path: forwardRate/r, on: Component(id=h type=gateHHratesTauInf), from forwardRate; Component(id=null type=nax_h_alpha_rate)
    h_alpha = h_forwardRate_r ? path based, prefix = h_
    
    ? DerivedVariable is based on path: reverseRate/r, on: Component(id=h type=gateHHratesTauInf), from reverseRate; Component(id=null type=nax_h_beta_rate)
    h_beta = h_reverseRate_r ? path based, prefix = h_
    
    h_steadyState_x = h_steadyState_rate  / (1 + exp(0 - (v -  h_steadyState_midpoint )/ h_steadyState_scale )) ? evaluable
    h_timeCourse_V = v /  h_timeCourse_VOLT_SCALE
    h_timeCourse_ALPHA = h_alpha  *  h_timeCourse_TIME_SCALE
    h_timeCourse_BETA = h_beta  *  h_timeCourse_TIME_SCALE
    if (( h_timeCourse_ALPHA  +  h_timeCourse_BETA ) == 0)  { 
        h_timeCourse_t = h_timeCourse_hmin  *  h_timeCourse_TIME_SCALE
    } else  { 
        h_timeCourse_t = 1/( h_timeCourse_ALPHA + h_timeCourse_BETA ) *  h_timeCourse_TIME_SCALE
    }
    
    ? DerivedVariable is based on path: steadyState/x, on: Component(id=h type=gateHHratesTauInf), from steadyState; Component(id=null type=HHSigmoidVariable)
    h_inf = h_steadyState_x ? path based, prefix = h_
    
    ? DerivedVariable is based on path: timeCourse/t, on: Component(id=h type=gateHHratesTauInf), from timeCourse; Component(id=null type=nax_h_tau)
    h_tauUnscaled = h_timeCourse_t / h_rateScale
    if (h_tauUnscaled < h_timeCourse_hmin) {
        h_tau = h_timeCourse_hmin
    } else {
        h_tau = h_tauUnscaled
    }
    
     
    rate_m_q = ( m_inf  -  m_q ) /  m_tau ? Note units of all quantities used here need to be consistent!
    
     
    
     
    
     
    
     
    
     
    rate_h_q = ( h_inf  -  h_q ) /  h_tau ? Note units of all quantities used here need to be consistent!
    
     
    
     
    
     
    
     
    
     
    
     
    
}
