TITLE Mod file for component: Component(id=cadad_RE_soma type=concentrationModel)

COMMENT

    This NEURON file has been generated by org.neuroml.export (see https://github.com/NeuroML/org.neuroml.export)
         org.neuroml.export  v1.11.0
         org.neuroml.model   v1.11.0
         jLEMS               v0.12.0

ENDCOMMENT

NEURON {
    SUFFIX cadad_RE_soma
    USEION ca READ cai, cao, ica WRITE cai VALENCE 2
    RANGE cai
    RANGE cao
    GLOBAL initialConcentration
    GLOBAL initialExtConcentration
    
}

UNITS {
    
    (nA) = (nanoamp)
    (uA) = (microamp)
    (mA) = (milliamp)
    (A) = (amp)
    (mV) = (millivolt)
    (mS) = (millisiemens)
    (uS) = (microsiemens)
    (nF) = (nanofarad)
    (molar) = (1/liter)
    (kHz) = (kilohertz)
    (mM) = (millimolar)
    (um) = (micrometer)
    (umol) = (micromole)
    (pC) = (picocoulomb)
    (S) = (siemens)
    
}

PARAMETER {
    surfaceArea (cm2)
    iCa (nA)
    initialConcentration (mM)
    initialExtConcentration (mM)
    
}

ASSIGNED {
    cai (mM)
    cao (mM)
    ica (mA/cm2)
    i__cadad_RE_soma (mA/cm2)
    diam (um)                               : Added to facilitate access to section's diam
    area (um2)                              : Added to facilitate access to section's area
    
}

STATE {
    concentration (mM) : dimension: concentration
    extConcentration (mM) : dimension: concentration
    
}

INITIAL {
    initialConcentration = cai
    initialExtConcentration = cao
    rates()
    rates() ? To ensure correct initialisation.
    
    concentration = initialConcentration
    
    extConcentration = initialExtConcentration
    
}

BREAKPOINT {
    
    rates()
    
    cai = concentration
    
    
}

PROCEDURE rates() {
    
    surfaceArea = (1e-08)*(area)   : surfaceArea has units (cm2), area (built in to NEURON) is in um^2...
    
    iCa = (1e6) * (-1 * ica * surfaceArea) :   iCa has units (nA) ; ica (built in to NEURON) has units (mA/cm2)...
    
    
     
    
}

