TITLE Mod file for component: Component(id=cal type=ionChannelHH)

COMMENT

    This NEURON file has been generated by org.neuroml.export (see https://github.com/NeuroML/org.neuroml.export)
         org.neuroml.export  v1.11.0
         org.neuroml.model   v1.11.0
         jLEMS               v0.12.0

ENDCOMMENT

NEURON {
    SUFFIX cal
    USEION ca READ eca WRITE ica VALENCE 2 ? Assuming valence = 2 (Ca ion); TODO check this!!
    
    RANGE gion
    RANGE i__cal : a copy of the variable for current which makes it easier to access from outside the mod file
    RANGE gmax                              : Will be changed when ion channel mechanism placed on cell!
    RANGE conductance                       : parameter
    RANGE g                                 : exposure
    RANGE fopen                             : exposure
    RANGE ConductanceScalingCaDependent_CONC_SCALE: parameter
    RANGE ConductanceScalingCaDependent_ki  : parameter
    RANGE ConductanceScalingCaDependent_factor: exposure
    RANGE m_instances                       : parameter
    RANGE m_alpha                           : exposure
    RANGE m_beta                            : exposure
    RANGE m_tau                             : exposure
    RANGE m_inf                             : exposure
    RANGE m_rateScale                       : exposure
    RANGE m_fcond                           : exposure
    RANGE m_forwardRate_rate                : parameter
    RANGE m_forwardRate_midpoint            : parameter
    RANGE m_forwardRate_scale               : parameter
    RANGE m_forwardRate_r                   : exposure
    RANGE m_reverseRate_rate                : parameter
    RANGE m_reverseRate_midpoint            : parameter
    RANGE m_reverseRate_scale               : parameter
    RANGE m_reverseRate_r                   : exposure
    RANGE m_timeCourse_TIME_SCALE           : parameter
    RANGE m_timeCourse_VOLT_SCALE           : parameter
    RANGE m_timeCourse_mmin                 : parameter
    RANGE m_timeCourse_a0m                  : parameter
    RANGE m_timeCourse_zetam                : parameter
    RANGE m_timeCourse_gmm                  : parameter
    RANGE m_timeCourse_vhalfm               : parameter
    RANGE m_timeCourse_t                    : exposure
    RANGE m_q10Settings_q10Factor           : parameter
    RANGE m_q10Settings_experimentalTemp    : parameter
    RANGE m_q10Settings_TENDEGREES          : parameter
    RANGE m_q10Settings_q10                 : exposure
    RANGE ConductanceScalingCaDependent_ca_conc: derived variable
    RANGE m_forwardRate_x                   : derived variable
    RANGE m_timeCourse_V                    : derived variable
    RANGE m_tauUnscaled                     : derived variable
    RANGE conductanceScale                  : derived variable
    RANGE fopen0                            : derived variable
    
}

UNITS {
    
    (nA) = (nanoamp)
    (uA) = (microamp)
    (mA) = (milliamp)
    (A) = (amp)
    (mV) = (millivolt)
    (mS) = (millisiemens)
    (uS) = (microsiemens)
    (nF) = (nanofarad)
    (molar) = (1/liter)
    (kHz) = (kilohertz)
    (mM) = (millimolar)
    (um) = (micrometer)
    (umol) = (micromole)
    (pC) = (picocoulomb)
    (S) = (siemens)
    
}

PARAMETER {
    
    gmax = 0  (S/cm2)                       : Will be changed when ion channel mechanism placed on cell!
    
    conductance = 1.0E-5 (uS)              : was: 1.0E-11 (conductance)
    ConductanceScalingCaDependent_CONC_SCALE = 1 (mM): was: 1.0 (concentration)
    ConductanceScalingCaDependent_ki = 0.001 : was: 0.001 (none)
    m_instances = 2                        : was: 2.0 (none)
    m_forwardRate_rate = 156.90001 (kHz)   : was: 156900.0 (per_time)
    m_forwardRate_midpoint = 81.5 (mV)     : was: 0.0815 (voltage)
    m_forwardRate_scale = 10 (mV)          : was: 0.01 (voltage)
    m_reverseRate_rate = 0.29000002 (kHz)  : was: 290.0 (per_time)
    m_reverseRate_midpoint = 0 (mV)        : was: 0.0 (voltage)
    m_reverseRate_scale = -10.86 (mV)      : was: -0.01086 (voltage)
    m_timeCourse_TIME_SCALE = 1 (ms)       : was: 0.001 (time)
    m_timeCourse_VOLT_SCALE = 1 (mV)       : was: 0.001 (voltage)
    m_timeCourse_mmin = 0.2 (ms)           : was: 2.0E-4 (time)
    m_timeCourse_a0m = 0.1                 : was: 0.1 (none)
    m_timeCourse_zetam = 2                 : was: 2.0 (none)
    m_timeCourse_gmm = 0.1                 : was: 0.1 (none)
    m_timeCourse_vhalfm = 4                : was: 4.0 (none)
    m_q10Settings_q10Factor = 5            : was: 5.0 (none)
    m_q10Settings_experimentalTemp = 298.15 (K): was: 298.15 (temperature)
    m_q10Settings_TENDEGREES = 10 (K)      : was: 10.0 (temperature)
}

ASSIGNED {
    
    gion   (S/cm2)                          : Transient conductance density of the channel? Standard Assigned variables with ionChannel
    v (mV)
    celsius (degC)
    temperature (K)
    eca (mV)
    ica (mA/cm2)
    i__cal (mA/cm2)
    
    cai (mM)
    
    cao (mM)   
    ConductanceScalingCaDependent_ca_conc   : derived variable
    ConductanceScalingCaDependent_factor    : derived variable
    m_forwardRate_x                         : derived variable
    
    m_forwardRate_r (kHz)                   : conditional derived var...
    m_reverseRate_r (kHz)                   : derived variable
    m_timeCourse_V                          : derived variable
    
    m_timeCourse_t (ms)                     : conditional derived var...
    m_q10Settings_q10                       : derived variable
    m_rateScale                             : derived variable
    m_alpha (kHz)                           : derived variable
    m_beta (kHz)                            : derived variable
    m_fcond                                 : derived variable
    m_inf                                   : derived variable
    m_tauUnscaled (ms)                      : derived variable
    m_tau (ms)                              : derived variable
    conductanceScale                        : derived variable
    fopen0                                  : derived variable
    fopen                                   : derived variable
    g (uS)                                  : derived variable
    rate_m_q (/ms)
    
}

STATE {
    m_q  : dimension: none
    
}

INITIAL {
    temperature = celsius + 273.15
    
    rates()
    rates() ? To ensure correct initialisation.
    
    m_q = m_inf
    
}

BREAKPOINT {
    
    SOLVE states METHOD cnexp
    
    ? DerivedVariable is based on path: conductanceScaling[*]/factor, on: Component(id=cal type=ionChannelHH), from conductanceScaling; Component(id=null type=cal_scale)
    ? multiply applied to all instances of factor in: <conductanceScaling> ([Component(id=null type=cal_scale)]))
    conductanceScale = ConductanceScalingCaDependent_factor ? path based, prefix = 
    
    ? DerivedVariable is based on path: gates[*]/fcond, on: Component(id=cal type=ionChannelHH), from gates; Component(id=m type=gateHHratesTau)
    ? multiply applied to all instances of fcond in: <gates> ([Component(id=m type=gateHHratesTau)]))
    fopen0 = m_fcond ? path based, prefix = 
    
    fopen = conductanceScale  *  fopen0 ? evaluable
    g = conductance  *  fopen ? evaluable
    gion = gmax * fopen 
    
    ica = gion * (v - eca)
    i__cal =  -1 * ica : set this variable to the current also - note -1 as channel current convention for LEMS used!
    
}

DERIVATIVE states {
    rates()
    m_q' = rate_m_q 
    
}

PROCEDURE rates() {
    LOCAL caConc
    
    caConc = cai
       
    ConductanceScalingCaDependent_ca_conc = caConc /  ConductanceScalingCaDependent_CONC_SCALE ? evaluable
    ConductanceScalingCaDependent_factor = ConductanceScalingCaDependent_ki  / ( ConductanceScalingCaDependent_ki  +  ConductanceScalingCaDependent_ca_conc ) ? evaluable
    m_forwardRate_x = (v -  m_forwardRate_midpoint ) /  m_forwardRate_scale ? evaluable
    if (m_forwardRate_x  != 0)  { 
        m_forwardRate_r = m_forwardRate_rate  *  m_forwardRate_x  / (1 - exp(0 -  m_forwardRate_x )) ? evaluable cdv
    } else if (m_forwardRate_x  == 0)  { 
        m_forwardRate_r = m_forwardRate_rate ? evaluable cdv
    }
    
    m_reverseRate_r = m_reverseRate_rate  * exp((v -  m_reverseRate_midpoint )/ m_reverseRate_scale ) ? evaluable
    m_timeCourse_V = v /  m_timeCourse_VOLT_SCALE ? evaluable
    if (exp(0.0378 *  m_timeCourse_zetam  *  m_timeCourse_gmm  * ( m_timeCourse_V  -  m_timeCourse_vhalfm )) / ( m_timeCourse_a0m  * (1 + exp(0.0378 *  m_timeCourse_zetam  * ( m_timeCourse_V  -  m_timeCourse_vhalfm )))) *  m_timeCourse_TIME_SCALE  <  m_timeCourse_mmin)  { 
        m_timeCourse_t = m_timeCourse_mmin ? evaluable cdv
    } else  { 
        m_timeCourse_t = exp(0.0378 *  m_timeCourse_zetam  *  m_timeCourse_gmm  * ( m_timeCourse_V  -  m_timeCourse_vhalfm )) / ( m_timeCourse_a0m  * (1 + exp(0.0378 *  m_timeCourse_zetam  * ( m_timeCourse_V  -  m_timeCourse_vhalfm )))) *  m_timeCourse_TIME_SCALE ? evaluable cdv
    }
    
    m_q10Settings_q10 = m_q10Settings_q10Factor ^((temperature -  m_q10Settings_experimentalTemp )/ m_q10Settings_TENDEGREES ) ? evaluable
    ? DerivedVariable is based on path: q10Settings[*]/q10, on: Component(id=m type=gateHHratesTau), from q10Settings; Component(id=null type=q10ExpTemp)
    ? multiply applied to all instances of q10 in: <q10Settings> ([Component(id=null type=q10ExpTemp)]))
    m_rateScale = m_q10Settings_q10 ? path based, prefix = m_
    
    ? DerivedVariable is based on path: forwardRate/r, on: Component(id=m type=gateHHratesTau), from forwardRate; Component(id=null type=HHExpLinearRate)
    m_alpha = m_forwardRate_r ? path based, prefix = m_
    
    ? DerivedVariable is based on path: reverseRate/r, on: Component(id=m type=gateHHratesTau), from reverseRate; Component(id=null type=HHExpRate)
    m_beta = m_reverseRate_r ? path based, prefix = m_
    
    m_fcond = m_q ^ m_instances ? evaluable
    m_inf = m_alpha /( m_alpha + m_beta ) ? evaluable
    ? DerivedVariable is based on path: timeCourse/t, on: Component(id=m type=gateHHratesTau), from timeCourse; Component(id=null type=cal_m_tau)
    m_tauUnscaled = m_timeCourse_t ? path based, prefix = m_
    
    m_tau = m_tauUnscaled  /  m_rateScale ? evaluable
    
     
    
     
    rate_m_q = ( m_inf  -  m_q ) /  m_tau ? Note units of all quantities used here need to be consistent!
    
     
    
     
    
     
    
     
    
     
    
}

