'''
Neuron simulator export for:

Components:
    null (Type: notes)
    cadad_IT2_dend_all (Type: cadad:  cainf=2.4E-4 (SI concentration) taur=0.09911468522820001 (SI time) depth=1.1940860792299998E-7 (SI length) Faraday=96485.3 (SI charge_per_mole) AREA_SCALE=1.0 (SI area) LENGTH_SCALE=1.0 (SI length))
    cadad_IT2_soma (Type: cadad:  cainf=2.4E-4 (SI concentration) taur=0.09911468522820001 (SI time) depth=1.1940860792299998E-7 (SI length) Faraday=96485.3 (SI charge_per_mole) AREA_SCALE=1.0 (SI area) LENGTH_SCALE=1.0 (SI length))
    can (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    cat (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    cal (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    ih (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    kap (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    pas (Type: ionChannelPassive:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    kBK (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    kdr (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    kdr_soma (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    nax (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    IT2_reduced_cell_0_0 (Type: cell)
    pg (Type: pulseGenerator:  delay=0.2 (SI time) duration=1.6 (SI time) amplitude=3.0E-10 (SI current))
    IT2_reduced_cell_net (Type: networkWithTemperature:  temperature=307.15 (SI temperature))
    IT2_reduced_cell_step_test (Type: Simulation:  length=2.0 (SI time) step=1.0E-5 (SI time))


    This NEURON file has been generated by org.neuroml.export (see https://github.com/NeuroML/org.neuroml.export)
         org.neuroml.export  v1.11.0
         org.neuroml.model   v1.11.0
         jLEMS               v0.12.0

'''

import neuron

import time
import datetime
import sys

import hashlib
h = neuron.h
h.load_file("nrngui.hoc")

h("objref p")
h("p = new PythonObject()")

class NeuronSimulation():

    def __init__(self, tstop, dt=None, seed=12345, abs_tol=None, rel_tol=None):

        print("\n    Starting simulation in NEURON of %sms generated from NeuroML2 model...\n"%tstop)

        self.setup_start = time.time()
        self.seed = seed
        self.abs_tol = abs_tol
        self.rel_tol = rel_tol
        self.randoms = []
        self.next_global_id = 0  # Used in Random123 classes for elements using random(), etc. 

        self.next_spiking_input_id = 0  # Used in Random123 classes for elements using random(), etc. 

        '''
        Adding simulation Component(id=IT2_reduced_cell_step_test type=Simulation) of network/component: IT2_reduced_cell_net (Type: networkWithTemperature:  temperature=307.15 (SI temperature))
        
        '''

        # Temperature used for network: 307.15 K
        h.celsius = 307.15 - 273.15

        # ######################   Population: IT2_reduced_cellpop
        print("Population IT2_reduced_cellpop contains 1 instance(s) of component: IT2_reduced_cell_0_0 of type: cell")

        print("Setting the default initial concentrations for ca (used in IT2_reduced_cell_0_0) to 5.0E-5 mM (internal), 2.0 mM (external)")
        h("cai0_ca_ion = 5.0E-5")
        h("cao0_ca_ion = 2.0")

        print("Setting the default initial concentrations for ca (used in IT2_reduced_cell_0_0) to 5.0E-5 mM (internal), 2.0 mM (external)")
        h("cai0_ca_ion = 5.0E-5")
        h("cao0_ca_ion = 2.0")

        h.load_file("IT2_reduced_cell_0_0.hoc")
        a_IT2_reduced_cellpop = []
        h("{ n_IT2_reduced_cellpop = 1 }")
        h("objectvar a_IT2_reduced_cellpop[n_IT2_reduced_cellpop]")
        for i in range(int(h.n_IT2_reduced_cellpop)):
            h("a_IT2_reduced_cellpop[%i] = new IT2_reduced_cell_0_0()"%i)
            h("access a_IT2_reduced_cellpop[%i].soma"%i)

            self.next_global_id+=1


        h("proc initialiseV_IT2_reduced_cellpop() { for i = 0, n_IT2_reduced_cellpop-1 { a_IT2_reduced_cellpop[i].set_initial_v() } }")
        h("objref fih_IT2_reduced_cellpop")
        h('{fih_IT2_reduced_cellpop = new FInitializeHandler(0, "initialiseV_IT2_reduced_cellpop()")}')

        h("proc initialiseIons_IT2_reduced_cellpop() { for i = 0, n_IT2_reduced_cellpop-1 { a_IT2_reduced_cellpop[i].set_initial_ion_properties() } }")
        h("objref fih_ion_IT2_reduced_cellpop")
        h('{fih_ion_IT2_reduced_cellpop = new FInitializeHandler(1, "initialiseIons_IT2_reduced_cellpop()")}')

        print("Processing 1 input lists")

        # ######################   Input List: input_list
        # Adding single input: Component(id=0 type=input)
        h("objref input_list_0")
        h("a_IT2_reduced_cellpop[0].soma { input_list_0 = new pg(0.5) } ")

        print("Finished processing 1 input lists")

        trec = h.Vector()
        trec.record(h._ref_t)

        h.tstop = tstop

        if self.abs_tol is not None and self.rel_tol is not None:
            cvode = h.CVode()
            cvode.active(1)
            cvode.atol(self.abs_tol)
            cvode.rtol(self.rel_tol)
        else:
            h.dt = dt
            h.steps_per_ms = 1/h.dt

        # ######################   Display: self.display_DispPop__IT2_reduced_cellpop
        self.display_DispPop__IT2_reduced_cellpop = h.Graph(0)
        self.display_DispPop__IT2_reduced_cellpop.size(0,h.tstop,-80.0,50.0)
        self.display_DispPop__IT2_reduced_cellpop.view(0, -80.0, h.tstop, 130.0, 80, 330, 330, 250)
        h.graphList[0].append(self.display_DispPop__IT2_reduced_cellpop)
        # Line, plotting: IT2_reduced_cellpop[0]/v
        self.display_DispPop__IT2_reduced_cellpop.addexpr("a_IT2_reduced_cellpop[0].soma.v(0.5)", "a_IT2_reduced_cellpop[0].soma.v(0.5)", 1, 1, 0.8, 0.9, 2)



        # ######################   File to save: IT2_reduced_cell_step_test.IT2_reduced_cellpop.v.dat (Volts_file__IT2_reduced_cellpop)
        # Column: IT2_reduced_cellpop[0]/v
        h(' objectvar v_v_IT2_reduced_cellpop_0__v_Volts_file__IT2_reduced_cellpop ')
        h(' { v_v_IT2_reduced_cellpop_0__v_Volts_file__IT2_reduced_cellpop = new Vector() } ')
        h(' { v_v_IT2_reduced_cellpop_0__v_Volts_file__IT2_reduced_cellpop.record(&a_IT2_reduced_cellpop[0].soma.v(0.5)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_v_IT2_reduced_cellpop_0__v_Volts_file__IT2_reduced_cellpop.resize((h.tstop * h.steps_per_ms) + 1)

        # ######################   File to save: time.dat (time)
        # Column: time
        h(' objectvar v_time ')
        h(' { v_time = new Vector() } ')
        h(' { v_time.record(&t) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_time.resize((h.tstop * h.steps_per_ms) + 1)

        # ######################   File to save: IT2_reduced_cell_step_test.IT2_reduced_cellpop.spikes (Spikes_file__IT2_reduced_cellpop)
        h(' objectvar spiketimes_Spikes_file__IT2_reduced_cellpop, t_spiketimes_Spikes_file__IT2_reduced_cellpop ')
        h(' { spiketimes_Spikes_file__IT2_reduced_cellpop = new Vector() } ')
        h(' { t_spiketimes_Spikes_file__IT2_reduced_cellpop = new Vector() } ')
        h(' objref netConnSpike_Spikes_file__IT2_reduced_cellpop, nil ')
        # Column: IT2_reduced_cellpop[0] (0) a_IT2_reduced_cellpop[0].soma
        h(' a_IT2_reduced_cellpop[0].soma { netConnSpike_Spikes_file__IT2_reduced_cellpop = new NetCon(&v(0.5), nil, 5.0, 0, 1) } ')
        h(' { netConnSpike_Spikes_file__IT2_reduced_cellpop.record(t_spiketimes_Spikes_file__IT2_reduced_cellpop, spiketimes_Spikes_file__IT2_reduced_cellpop, 0) } ')

        self.initialized = False

        self.sim_end = -1 # will be overwritten

        setup_end = time.time()
        self.setup_time = setup_end - self.setup_start
        print("Setting up the network to simulate took %f seconds"%(self.setup_time))

        h.nrncontrolmenu()


    def run(self):

        self.initialized = True
        sim_start = time.time()
        if self.abs_tol is not None and self.rel_tol is not None:
            print("Running a simulation of %sms (cvode abs_tol = %sms, rel_tol = %sms; seed=%s)" % (h.tstop, self.abs_tol, self.rel_tol, self.seed))
        else:
            print("Running a simulation of %sms (dt = %sms; seed=%s)" % (h.tstop, h.dt, self.seed))

        try:
            h.run()
        except Exception as e:
            print("Exception running NEURON: %s" % (e))
            return


        self.sim_end = time.time()
        self.sim_time = self.sim_end - sim_start
        print("Finished NEURON simulation in %f seconds (%f mins)..."%(self.sim_time, self.sim_time/60.0))

        try:
            self.save_results()
        except Exception as e:
            print("Exception saving results of NEURON simulation: %s" % (e))
            return


    def advance(self):

        if not self.initialized:
            h.finitialize()
            self.initialized = True

        h.fadvance()


    ###############################################################################
    # Hash function to use in generation of random value
    # This is copied from NetPyNE: https://github.com/Neurosim-lab/netpyne/blob/master/netpyne/simFuncs.py
    ###############################################################################
    def _id32 (self,obj): 
        return int(hashlib.md5(obj.encode('utf-8')).hexdigest()[0:8],16)  # convert 8 first chars of md5 hash in base 16 to int


    ###############################################################################
    # Initialize the stim randomizer
    # This is copied from NetPyNE: https://github.com/Neurosim-lab/netpyne/blob/master/netpyne/simFuncs.py
    ###############################################################################
    def _init_stim_randomizer(self,rand, stimType, gid, seed): 
        #print("INIT STIM  %s; %s; %s; %s"%(rand, stimType, gid, seed))
        rand.Random123(self._id32(stimType), gid, seed)


    def save_results(self):

        print("Saving results at t=%s..."%h.t)

        if self.sim_end < 0: self.sim_end = time.time()

        self.display_DispPop__IT2_reduced_cellpop.exec_menu("View = plot")

        # ######################   File to save: time.dat (time). Note, saving in SI units
        py_v_time = [ t/1000 for t in h.v_time.to_python() ]  # Convert to Python list for speed...

        f_time_f2 = open('time.dat', 'w')
        num_points = len(py_v_time)  # Simulation may have been stopped before tstop...

        for i in range(num_points):
            f_time_f2.write('%f'% py_v_time[i])  # Save in SI units...
        f_time_f2.close()
        print("Saved data to: time.dat")

        # ######################   File to save: IT2_reduced_cell_step_test.IT2_reduced_cellpop.v.dat (Volts_file__IT2_reduced_cellpop). Note, saving in SI units
        py_v_v_IT2_reduced_cellpop_0__v_Volts_file__IT2_reduced_cellpop = [ float(x  / 1000.0) for x in h.v_v_IT2_reduced_cellpop_0__v_Volts_file__IT2_reduced_cellpop.to_python() ]  # Convert to Python list for speed, variable has dim: voltage

        f_Volts_file__IT2_reduced_cellpop_f2 = open('IT2_reduced_cell_step_test.IT2_reduced_cellpop.v.dat', 'w')
        num_points = len(py_v_time)  # Simulation may have been stopped before tstop...

        for i in range(num_points):
            f_Volts_file__IT2_reduced_cellpop_f2.write('%e\t%e\t\n' % (py_v_time[i], py_v_v_IT2_reduced_cellpop_0__v_Volts_file__IT2_reduced_cellpop[i], ))
        f_Volts_file__IT2_reduced_cellpop_f2.close()
        print("Saved data to: IT2_reduced_cell_step_test.IT2_reduced_cellpop.v.dat")

        # ######################   File to save: IT2_reduced_cell_step_test.IT2_reduced_cellpop.spikes (Spikes_file__IT2_reduced_cellpop). Note, saving in SI units

        f_Spikes_file__IT2_reduced_cellpop_f2 = open('IT2_reduced_cell_step_test.IT2_reduced_cellpop.spikes', 'w')
        h(' objref netConnSpike_Spikes_file__IT2_reduced_cellpop ')
        spike_ids = h.spiketimes_Spikes_file__IT2_reduced_cellpop.to_python()  
        spike_times = h.t_spiketimes_Spikes_file__IT2_reduced_cellpop.to_python()
        for i, id in enumerate(spike_ids):
            # Saving in format: ID_TIME
            f_Spikes_file__IT2_reduced_cellpop_f2.write("%i\t%s\n"%(id,spike_times[i]/1000.0))
        f_Spikes_file__IT2_reduced_cellpop_f2.close()
        print("Saved data to: IT2_reduced_cell_step_test.IT2_reduced_cellpop.spikes")

        save_end = time.time()
        save_time = save_end - self.sim_end
        print("Finished saving results in %f seconds"%(save_time))

        print("Done")

if __name__ == '__main__':

    ns = NeuronSimulation(tstop=2000.0, dt=0.01, seed=12345, abs_tol=None, rel_tol=None)

    ns.run()

