'''
Neuron simulator export for:

Components:
    null (Type: notes)
    cadad_IT2_dend_all (Type: cadad:  cainf=2.4E-4 (SI concentration) taur=0.09911468522820001 (SI time) depth=1.1940860792299998E-7 (SI length) Faraday=96485.3 (SI charge_per_mole) AREA_SCALE=1.0 (SI area) LENGTH_SCALE=1.0 (SI length))
    cadad_IT2_soma (Type: cadad:  cainf=2.4E-4 (SI concentration) taur=0.09911468522820001 (SI time) depth=1.1940860792299998E-7 (SI length) Faraday=96485.3 (SI charge_per_mole) AREA_SCALE=1.0 (SI area) LENGTH_SCALE=1.0 (SI length))
    can (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    cat (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    cal (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    ih (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    kap (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    pas (Type: ionChannelPassive:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    kBK (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    kdr (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    kdr_soma (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    nax (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    IT2_reduced_cell_0_0 (Type: cell)
    input_0_2nA (Type: pulseGenerator:  delay=0.2 (SI time) duration=0.7000000000000001 (SI time) amplitude=2.0000000000000003E-10 (SI current))
    input_0_3nA (Type: pulseGenerator:  delay=0.2 (SI time) duration=0.7000000000000001 (SI time) amplitude=3.0E-10 (SI current))
    input_0_4nA (Type: pulseGenerator:  delay=0.2 (SI time) duration=0.7000000000000001 (SI time) amplitude=4.0000000000000007E-10 (SI current))
    input_0_5nA (Type: pulseGenerator:  delay=0.2 (SI time) duration=0.7000000000000001 (SI time) amplitude=5.0E-10 (SI current))
    network_of_IT2_reduced_cell_0_0 (Type: networkWithTemperature:  temperature=307.15 (SI temperature))
    iv_IT2_reduced_cell_0_0 (Type: Simulation:  length=1.2 (SI time) step=5.0E-5 (SI time))


    This NEURON file has been generated by org.neuroml.export (see https://github.com/NeuroML/org.neuroml.export)
         org.neuroml.export  v1.11.0
         org.neuroml.model   v1.11.0
         jLEMS               v0.12.0

'''

import neuron

import time
import datetime
import sys

import hashlib
h = neuron.h
h.load_file("stdlib.hoc")

h.load_file("stdgui.hoc")

h("objref p")
h("p = new PythonObject()")

class NeuronSimulation():

    def __init__(self, tstop, dt=None, seed=12345, abs_tol=None, rel_tol=None):

        print("\n    Starting simulation in NEURON of %sms generated from NeuroML2 model...\n"%tstop)

        self.setup_start = time.time()
        self.seed = seed
        self.abs_tol = abs_tol
        self.rel_tol = rel_tol
        self.randoms = []
        self.next_global_id = 0  # Used in Random123 classes for elements using random(), etc. 

        self.next_spiking_input_id = 0  # Used in Random123 classes for elements using random(), etc. 

        '''
        Adding simulation Component(id=iv_IT2_reduced_cell_0_0 type=Simulation) of network/component: network_of_IT2_reduced_cell_0_0 (Type: networkWithTemperature:  temperature=307.15 (SI temperature))
        
        '''

        # Temperature used for network: 307.15 K
        h.celsius = 307.15 - 273.15

        # ######################   Population: population_of_IT2_reduced_cell_0_0
        print("Population population_of_IT2_reduced_cell_0_0 contains 4 instance(s) of component: IT2_reduced_cell_0_0 of type: cell")

        print("Setting the default initial concentrations for ca (used in IT2_reduced_cell_0_0) to 5.0E-5 mM (internal), 2.0 mM (external)")
        h("cai0_ca_ion = 5.0E-5")
        h("cao0_ca_ion = 2.0")

        print("Setting the default initial concentrations for ca (used in IT2_reduced_cell_0_0) to 5.0E-5 mM (internal), 2.0 mM (external)")
        h("cai0_ca_ion = 5.0E-5")
        h("cao0_ca_ion = 2.0")

        h.load_file("IT2_reduced_cell_0_0.hoc")
        a_population_of_IT2_reduced_cell_0_0 = []
        h("{ n_population_of_IT2_reduced_cell_0_0 = 4 }")
        h("objectvar a_population_of_IT2_reduced_cell_0_0[n_population_of_IT2_reduced_cell_0_0]")
        for i in range(int(h.n_population_of_IT2_reduced_cell_0_0)):
            h("a_population_of_IT2_reduced_cell_0_0[%i] = new IT2_reduced_cell_0_0()"%i)
            h("access a_population_of_IT2_reduced_cell_0_0[%i].soma"%i)

            self.next_global_id+=1


        h("proc initialiseV_population_of_IT2_reduced_cell_0_0() { for i = 0, n_population_of_IT2_reduced_cell_0_0-1 { a_population_of_IT2_reduced_cell_0_0[i].set_initial_v() } }")
        h("objref fih_population_of_IT2_reduced_cell_0_0")
        h('{fih_population_of_IT2_reduced_cell_0_0 = new FInitializeHandler(0, "initialiseV_population_of_IT2_reduced_cell_0_0()")}')

        h("proc initialiseIons_population_of_IT2_reduced_cell_0_0() { for i = 0, n_population_of_IT2_reduced_cell_0_0-1 { a_population_of_IT2_reduced_cell_0_0[i].set_initial_ion_properties() } }")
        h("objref fih_ion_population_of_IT2_reduced_cell_0_0")
        h('{fih_ion_population_of_IT2_reduced_cell_0_0 = new FInitializeHandler(1, "initialiseIons_population_of_IT2_reduced_cell_0_0()")}')

        print("Processing 4 input lists")

        # ######################   Input List: input_0_2nA
        # Adding single input: Component(id=0 type=input)
        h("objref input_0_2nA_0")
        h("a_population_of_IT2_reduced_cell_0_0[0].soma { input_0_2nA_0 = new input_0_2nA(0.5) } ")

        # ######################   Input List: input_0_3nA
        # Adding single input: Component(id=0 type=input)
        h("objref input_0_3nA_0")
        h("a_population_of_IT2_reduced_cell_0_0[1].soma { input_0_3nA_0 = new input_0_3nA(0.5) } ")

        # ######################   Input List: input_0_4nA
        # Adding single input: Component(id=0 type=input)
        h("objref input_0_4nA_0")
        h("a_population_of_IT2_reduced_cell_0_0[2].soma { input_0_4nA_0 = new input_0_4nA(0.5) } ")

        # ######################   Input List: input_0_5nA
        # Adding single input: Component(id=0 type=input)
        h("objref input_0_5nA_0")
        h("a_population_of_IT2_reduced_cell_0_0[3].soma { input_0_5nA_0 = new input_0_5nA(0.5) } ")

        print("Finished processing 4 input lists")

        trec = h.Vector()
        trec.record(h._ref_t)

        h.tstop = tstop

        if self.abs_tol is not None and self.rel_tol is not None:
            cvode = h.CVode()
            cvode.active(1)
            cvode.atol(self.abs_tol)
            cvode.rtol(self.rel_tol)
        else:
            h.dt = dt
            h.steps_per_ms = 1/h.dt



        # ######################   File to save: iv_IT2_reduced_cell_0_0.v.dat (Volts_file)
        # Column: population_of_IT2_reduced_cell_0_0[0]/v
        h(' objectvar v_v_cell0_Volts_file ')
        h(' { v_v_cell0_Volts_file = new Vector() } ')
        h(' { v_v_cell0_Volts_file.record(&a_population_of_IT2_reduced_cell_0_0[0].soma.v(0.5)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_v_cell0_Volts_file.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: population_of_IT2_reduced_cell_0_0[1]/v
        h(' objectvar v_v_cell1_Volts_file ')
        h(' { v_v_cell1_Volts_file = new Vector() } ')
        h(' { v_v_cell1_Volts_file.record(&a_population_of_IT2_reduced_cell_0_0[1].soma.v(0.5)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_v_cell1_Volts_file.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: population_of_IT2_reduced_cell_0_0[2]/v
        h(' objectvar v_v_cell2_Volts_file ')
        h(' { v_v_cell2_Volts_file = new Vector() } ')
        h(' { v_v_cell2_Volts_file.record(&a_population_of_IT2_reduced_cell_0_0[2].soma.v(0.5)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_v_cell2_Volts_file.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: population_of_IT2_reduced_cell_0_0[3]/v
        h(' objectvar v_v_cell3_Volts_file ')
        h(' { v_v_cell3_Volts_file = new Vector() } ')
        h(' { v_v_cell3_Volts_file.record(&a_population_of_IT2_reduced_cell_0_0[3].soma.v(0.5)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_v_cell3_Volts_file.resize((h.tstop * h.steps_per_ms) + 1)

        # ######################   File to save: time.dat (time)
        # Column: time
        h(' objectvar v_time ')
        h(' { v_time = new Vector() } ')
        h(' { v_time.record(&t) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_time.resize((h.tstop * h.steps_per_ms) + 1)

        self.initialized = False

        self.sim_end = -1 # will be overwritten

        setup_end = time.time()
        self.setup_time = setup_end - self.setup_start
        print("Setting up the network to simulate took %f seconds"%(self.setup_time))

    def run(self):

        self.initialized = True
        sim_start = time.time()
        if self.abs_tol is not None and self.rel_tol is not None:
            print("Running a simulation of %sms (cvode abs_tol = %sms, rel_tol = %sms; seed=%s)" % (h.tstop, self.abs_tol, self.rel_tol, self.seed))
        else:
            print("Running a simulation of %sms (dt = %sms; seed=%s)" % (h.tstop, h.dt, self.seed))

        try:
            h.run()
        except Exception as e:
            print("Exception running NEURON: %s" % (e))
            quit()


        self.sim_end = time.time()
        self.sim_time = self.sim_end - sim_start
        print("Finished NEURON simulation in %f seconds (%f mins)..."%(self.sim_time, self.sim_time/60.0))

        try:
            self.save_results()
        except Exception as e:
            print("Exception saving results of NEURON simulation: %s" % (e))
            quit()


    def advance(self):

        if not self.initialized:
            h.finitialize()
            self.initialized = True

        h.fadvance()


    ###############################################################################
    # Hash function to use in generation of random value
    # This is copied from NetPyNE: https://github.com/Neurosim-lab/netpyne/blob/master/netpyne/simFuncs.py
    ###############################################################################
    def _id32 (self,obj): 
        return int(hashlib.md5(obj.encode('utf-8')).hexdigest()[0:8],16)  # convert 8 first chars of md5 hash in base 16 to int


    ###############################################################################
    # Initialize the stim randomizer
    # This is copied from NetPyNE: https://github.com/Neurosim-lab/netpyne/blob/master/netpyne/simFuncs.py
    ###############################################################################
    def _init_stim_randomizer(self,rand, stimType, gid, seed): 
        #print("INIT STIM  %s; %s; %s; %s"%(rand, stimType, gid, seed))
        rand.Random123(self._id32(stimType), gid, seed)


    def save_results(self):

        print("Saving results at t=%s..."%h.t)

        if self.sim_end < 0: self.sim_end = time.time()


        # ######################   File to save: time.dat (time). Note, saving in SI units
        py_v_time = [ t/1000 for t in h.v_time.to_python() ]  # Convert to Python list for speed...

        f_time_f2 = open('time.dat', 'w')
        num_points = len(py_v_time)  # Simulation may have been stopped before tstop...

        for i in range(num_points):
            f_time_f2.write('%f'% py_v_time[i])  # Save in SI units...
        f_time_f2.close()
        print("Saved data to: time.dat")

        # ######################   File to save: iv_IT2_reduced_cell_0_0.v.dat (Volts_file). Note, saving in SI units
        py_v_v_cell0_Volts_file = [ float(x  / 1000.0) for x in h.v_v_cell0_Volts_file.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_v_cell1_Volts_file = [ float(x  / 1000.0) for x in h.v_v_cell1_Volts_file.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_v_cell2_Volts_file = [ float(x  / 1000.0) for x in h.v_v_cell2_Volts_file.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_v_cell3_Volts_file = [ float(x  / 1000.0) for x in h.v_v_cell3_Volts_file.to_python() ]  # Convert to Python list for speed, variable has dim: voltage

        f_Volts_file_f2 = open('iv_IT2_reduced_cell_0_0.v.dat', 'w')
        num_points = len(py_v_time)  # Simulation may have been stopped before tstop...

        for i in range(num_points):
            f_Volts_file_f2.write('%e\t%e\t%e\t%e\t%e\t\n' % (py_v_time[i], py_v_v_cell0_Volts_file[i], py_v_v_cell1_Volts_file[i], py_v_v_cell2_Volts_file[i], py_v_v_cell3_Volts_file[i], ))
        f_Volts_file_f2.close()
        print("Saved data to: iv_IT2_reduced_cell_0_0.v.dat")

        save_end = time.time()
        save_time = save_end - self.sim_end
        print("Finished saving results in %f seconds"%(save_time))

        print("Done")

        quit()


if __name__ == '__main__':

    ns = NeuronSimulation(tstop=1200.0, dt=0.05, seed=12345, abs_tol=None, rel_tol=None)

    ns.run()

