TITLE Mod file for component: Component(id=cadad_IT2_soma type=cadad)

COMMENT

    This NEURON file has been generated by org.neuroml.export (see https://github.com/NeuroML/org.neuroml.export)
         org.neuroml.export  v1.11.0
         org.neuroml.model   v1.11.0
         jLEMS               v0.12.0

ENDCOMMENT

NEURON {
    SUFFIX cadad_IT2_soma
    USEION ca READ cai, cao, ica WRITE cai VALENCE 2
    RANGE cai
    RANGE cao
    GLOBAL initialConcentration
    GLOBAL initialExtConcentration
    RANGE cainf                             : parameter
    RANGE taur                              : parameter
    RANGE depth                             : parameter
    RANGE Faraday                           : parameter
    RANGE AREA_SCALE                        : parameter
    RANGE LENGTH_SCALE                      : parameter
    RANGE currDensCa                        : derived variable
    
}

UNITS {
    
    (nA) = (nanoamp)
    (uA) = (microamp)
    (mA) = (milliamp)
    (A) = (amp)
    (mV) = (millivolt)
    (mS) = (millisiemens)
    (uS) = (microsiemens)
    (nF) = (nanofarad)
    (molar) = (1/liter)
    (kHz) = (kilohertz)
    (mM) = (millimolar)
    (um) = (micrometer)
    (umol) = (micromole)
    (pC) = (picocoulomb)
    (S) = (siemens)
    
}

PARAMETER {
    surfaceArea (cm2)
    iCa (nA)
    initialConcentration (mM)
    initialExtConcentration (mM)
    
    cainf = 2.4E-4 (mM)                    : was: 2.4E-4 (concentration)
    taur = 99.114685 (ms)                  : was: 0.09911468522820001 (time)
    depth = 1.1940861E-5 (cm)              : was: 1.1940860792299998E-7 (length)
    Faraday = 9.6485302E10 (pC / umol)     : was: 96485.3 (charge_per_mole)
    AREA_SCALE = 10000 (cm2)               : was: 1.0 (area)
    LENGTH_SCALE = 100 (cm)                : was: 1.0 (length)
}

ASSIGNED {
    cai (mM)
    cao (mM)
    ica (mA/cm2)
    i__cadad_IT2_soma (mA/cm2)
    diam (um)                               : Added to facilitate access to section's diam
    area (um2)                              : Added to facilitate access to section's area
    currDensCa (nA / cm2)                   : derived variable
    rate_concentration (mM/ms)
    
}

STATE {
    concentration (mM) : dimension: concentration
    extConcentration (mM) : dimension: concentration
    
}

INITIAL {
    initialConcentration = cai
    initialExtConcentration = cao
    rates()
    rates() ? To ensure correct initialisation.
    
    concentration = initialConcentration
    
    extConcentration = initialExtConcentration
    
}

BREAKPOINT {
    
    SOLVE states METHOD cnexp
    
    
}

DERIVATIVE states {
    rates()
    concentration' = rate_concentration
    cai = concentration 
    
}

PROCEDURE rates() {
    
    surfaceArea = (1e-08)*(area)   : surfaceArea has units (cm2), area (built in to NEURON) is in um^2...
    
    iCa = (1e6) * (-1 * ica * surfaceArea) :   iCa has units (nA) ; ica (built in to NEURON) has units (mA/cm2)...
    
    currDensCa = iCa / surfaceArea ? evaluable
    rate_concentration = (  currDensCa  /(2*  Faraday  *  depth  )) - ((  concentration   -   cainf  ) /   taur  ) ? Note units of all quantities used here need to be consistent!
    
     
    
}

