TITLE Mod file for component: Component(id=kdr_soma type=ionChannelHH)

COMMENT

    This NEURON file has been generated by org.neuroml.export (see https://github.com/NeuroML/org.neuroml.export)
         org.neuroml.export  v1.11.0
         org.neuroml.model   v1.11.0
         jLEMS               v0.12.0

ENDCOMMENT

NEURON {
    SUFFIX kdr_soma
    USEION k WRITE ik VALENCE 1 ? Assuming valence = 1; TODO check this!!
    
    RANGE gion
    RANGE i__kdr_soma : a copy of the variable for current which makes it easier to access from outside the mod file
    RANGE gmax                              : Will be changed when ion channel mechanism placed on cell!
    RANGE conductance                       : parameter
    RANGE g                                 : exposure
    RANGE fopen                             : exposure
    RANGE n_instances                       : parameter
    RANGE n_tau                             : exposure
    RANGE n_inf                             : exposure
    RANGE n_rateScale                       : exposure
    RANGE n_fcond                           : exposure
    RANGE n_steadyState_VOLT_SCALE          : parameter
    RANGE n_steadyState_Celsius             : parameter
    RANGE n_steadyState_zetan               : parameter
    RANGE n_steadyState_sh                  : parameter
    RANGE n_steadyState_vhalfn              : parameter
    RANGE n_steadyState_x                   : exposure
    RANGE n_timeCourse_TIME_SCALE           : parameter
    RANGE n_timeCourse_VOLT_SCALE           : parameter
    RANGE n_timeCourse_nmax                 : parameter
    RANGE n_timeCourse_Celsius              : parameter
    RANGE n_timeCourse_zetan                : parameter
    RANGE n_timeCourse_sh                   : parameter
    RANGE n_timeCourse_gmn                  : parameter
    RANGE n_timeCourse_a0n                  : parameter
    RANGE n_timeCourse_vhalfn               : parameter
    RANGE n_timeCourse_t                    : exposure
    RANGE n_q10Settings_q10Factor           : parameter
    RANGE n_q10Settings_experimentalTemp    : parameter
    RANGE n_q10Settings_TENDEGREES          : parameter
    RANGE n_q10Settings_q10                 : exposure
    RANGE n_steadyState_V                   : derived variable
    RANGE n_timeCourse_V                    : derived variable
    RANGE n_tauUnscaled                     : derived variable
    RANGE conductanceScale                  : derived variable
    RANGE fopen0                            : derived variable
    
}

UNITS {
    
    (nA) = (nanoamp)
    (uA) = (microamp)
    (mA) = (milliamp)
    (A) = (amp)
    (mV) = (millivolt)
    (mS) = (millisiemens)
    (uS) = (microsiemens)
    (nF) = (nanofarad)
    (molar) = (1/liter)
    (kHz) = (kilohertz)
    (mM) = (millimolar)
    (um) = (micrometer)
    (umol) = (micromole)
    (pC) = (picocoulomb)
    (S) = (siemens)
    
}

PARAMETER {
    
    gmax = 0  (S/cm2)                       : Will be changed when ion channel mechanism placed on cell!
    
    conductance = 1.0E-5 (uS)              : was: 1.0E-11 (conductance)
    n_instances = 1                        : was: 1.0 (none)
    n_steadyState_VOLT_SCALE = 1 (mV)      : was: 0.001 (voltage)
    n_steadyState_Celsius = 24             : was: 24.0 (none)
    n_steadyState_zetan = -3               : was: -3.0 (none)
    n_steadyState_sh = 0                   : was: 0.0 (none)
    n_steadyState_vhalfn = 8               : was: 8.0 (none)
    n_timeCourse_TIME_SCALE = 1 (ms)       : was: 0.001 (time)
    n_timeCourse_VOLT_SCALE = 1 (mV)       : was: 0.001 (voltage)
    n_timeCourse_nmax = 20 (ms)            : was: 0.02 (time)
    n_timeCourse_Celsius = 24              : was: 24.0 (none)
    n_timeCourse_zetan = -3                : was: -3.0 (none)
    n_timeCourse_sh = 0                    : was: 0.0 (none)
    n_timeCourse_gmn = 0.7                 : was: 0.7 (none)
    n_timeCourse_a0n = 0.0075              : was: 0.0075 (none)
    n_timeCourse_vhalfn = 8                : was: 8.0 (none)
    n_q10Settings_q10Factor = 1            : was: 1.0 (none)
    n_q10Settings_experimentalTemp = 297.15 (K): was: 297.15 (temperature)
    n_q10Settings_TENDEGREES = 10 (K)      : was: 10.0 (temperature)
}

ASSIGNED {
    
    gion   (S/cm2)                          : Transient conductance density of the channel? Standard Assigned variables with ionChannel
    v (mV)
    celsius (degC)
    temperature (K)
    ek (mV)
    ik (mA/cm2)
    i__kdr_soma (mA/cm2)
    
    n_steadyState_V                         : derived variable
    n_steadyState_x                         : derived variable
    n_timeCourse_V                          : derived variable
    
    n_timeCourse_t (ms)                     : conditional derived var...
    n_q10Settings_q10                       : derived variable
    n_rateScale                             : derived variable
    n_fcond                                 : derived variable
    n_inf                                   : derived variable
    n_tauUnscaled (ms)                      : derived variable
    n_tau (ms)                              : derived variable
    conductanceScale                        : derived variable
    fopen0                                  : derived variable
    fopen                                   : derived variable
    g (uS)                                  : derived variable
    rate_n_q (/ms)
    
}

STATE {
    n_q  : dimension: none
    
}

INITIAL {
    ek = -104.0
    
    temperature = celsius + 273.15
    
    rates()
    rates() ? To ensure correct initialisation.
    
    n_q = n_inf
    
}

BREAKPOINT {
    
    SOLVE states METHOD cnexp
    
    ? DerivedVariable is based on path: conductanceScaling[*]/factor, on: Component(id=kdr_soma type=ionChannelHH), from conductanceScaling; null
    ? Path not present in component, using factor: 1
    
    conductanceScale = 1 
    
    ? DerivedVariable is based on path: gates[*]/fcond, on: Component(id=kdr_soma type=ionChannelHH), from gates; Component(id=n type=gateHHtauInf)
    ? multiply applied to all instances of fcond in: <gates> ([Component(id=n type=gateHHtauInf)]))
    fopen0 = n_fcond ? path based, prefix = 
    
    fopen = conductanceScale  *  fopen0 ? evaluable
    g = conductance  *  fopen ? evaluable
    gion = gmax * fopen 
    
    ik = gion * (v - ek)
    i__kdr_soma =  -1 * ik : set this variable to the current also - note -1 as channel current convention for LEMS used!
    
}

DERIVATIVE states {
    rates()
    n_q' = rate_n_q 
    
}

PROCEDURE rates() {
    
    n_steadyState_V = v /  n_steadyState_VOLT_SCALE ? evaluable
    n_steadyState_x = 1 / (1 + exp(1.e-3* n_steadyState_zetan *( n_steadyState_V - n_steadyState_vhalfn - n_steadyState_sh )*9.648e4/
                (8.315*(273.16+ n_steadyState_Celsius )))) ? evaluable
    n_timeCourse_V = v /  n_timeCourse_VOLT_SCALE ? evaluable
    if (exp(1.e-3* n_timeCourse_zetan * n_timeCourse_gmn *( n_timeCourse_V - n_timeCourse_vhalfn - n_timeCourse_sh )*9.648e4/(8.315*(273.16+ n_timeCourse_Celsius ))) / 
                    ( n_timeCourse_a0n  * (1 + exp(1.e-3* n_timeCourse_zetan *( n_timeCourse_V - n_timeCourse_vhalfn - n_timeCourse_sh )*9.648e4/(8.315*(273.16+ n_timeCourse_Celsius ))))) *  n_timeCourse_TIME_SCALE  <  n_timeCourse_nmax)  { 
        n_timeCourse_t = n_timeCourse_nmax ? evaluable cdv
    } else  { 
        n_timeCourse_t = exp(1.e-3* n_timeCourse_zetan * n_timeCourse_gmn *( n_timeCourse_V - n_timeCourse_vhalfn - n_timeCourse_sh )*9.648e4/(8.315*(273.16+ n_timeCourse_Celsius ))) / 
                    ( n_timeCourse_a0n  * (1 + exp(1.e-3* n_timeCourse_zetan *( n_timeCourse_V - n_timeCourse_vhalfn - n_timeCourse_sh )*9.648e4/(8.315*(273.16+ n_timeCourse_Celsius ))))) *  n_timeCourse_TIME_SCALE ? evaluable cdv
    }
    
    n_q10Settings_q10 = n_q10Settings_q10Factor ^((temperature -  n_q10Settings_experimentalTemp )/ n_q10Settings_TENDEGREES ) ? evaluable
    ? DerivedVariable is based on path: q10Settings[*]/q10, on: Component(id=n type=gateHHtauInf), from q10Settings; Component(id=null type=q10ExpTemp)
    ? multiply applied to all instances of q10 in: <q10Settings> ([Component(id=null type=q10ExpTemp)]))
    n_rateScale = n_q10Settings_q10 ? path based, prefix = n_
    
    n_fcond = n_q ^ n_instances ? evaluable
    ? DerivedVariable is based on path: steadyState/x, on: Component(id=n type=gateHHtauInf), from steadyState; Component(id=null type=kdr_soma_n_inf)
    n_inf = n_steadyState_x ? path based, prefix = n_
    
    ? DerivedVariable is based on path: timeCourse/t, on: Component(id=n type=gateHHtauInf), from timeCourse; Component(id=null type=kdr_soma_n_tau)
    n_tauUnscaled = n_timeCourse_t ? path based, prefix = n_
    
    n_tau = n_tauUnscaled  /  n_rateScale ? evaluable
    
     
    rate_n_q = ( n_inf  -  n_q ) /  n_tau ? Note units of all quantities used here need to be consistent!
    
     
    
     
    
     
    
     
    
}

